// pkgs.ts/diy-app/src/renderer_solid/components/AgentChatPanel.tsx
import { onMount, createEffect, For, Show } from "solid-js";
import { agentStore } from "../store/agentStore";
import { taskStore } from "../store/taskStore";

export function AgentChatPanel() {
    let inputRef: HTMLTextAreaElement | undefined;
    let bottomRef: HTMLDivElement | undefined;
    onMount(() => { agentStore.loadModels(); agentStore.loadAutoApprove(); });

    // 切换任务时以主进程的真实会话状态为准刷新模型，避免界面显示伪造默认值
    createEffect(() => {
        const uri = taskStore.selectedUri;
        if (uri) void agentStore.syncStatus(uri);
        else agentStore.setModel("");
    });

    const handleSend = () => {
        if (!inputRef || agentStore.sending) return;
        const t = inputRef.value.trim();
        if (!t) return;
        const uri = taskStore.selectedUri;
        if (!uri) return; // 未选中任务时不发送（task 级对话）
        inputRef.value = "";
        agentStore.sendMessage(uri, t);
        setTimeout(() => bottomRef?.scrollIntoView({ behavior: "smooth" }), 50);
    };

    return (
        <div class="flex flex-col h-full">
            {/* 顶栏：模型选择 + 操作 */}
            <div class="flex items-center gap-2 px-3 py-2 border-b shrink-0">
                <select
                    value={agentStore.activeModel ?? ""}
                    onChange={(e) => {
                        const id = e.currentTarget.value;
                        agentStore.setModel(id);
                        const uri = taskStore.selectedUri;
                        if (id && uri) agentStore.switchModel(uri, id);
                    }}
                    class="select select-bordered select-sm"
                >
                    {/* 占位项：没有真实会话时不能预选任何模型 */}
                    <option value="">（未指定 · 用 agent 默认模型）</option>
                    <For each={agentStore.models}>
                        {(m) => <option value={m.id}>{m.name}</option>}
                    </For>
                </select>
                <button class="btn btn-ghost btn-sm" onClick={() => agentStore.clearChat()}>
                    清空
                </button>
                <label class="flex items-center gap-1 text-xs opacity-60 cursor-pointer select-none">
                    <input
                        type="checkbox"
                        checked={agentStore.autoApprove}
                        onChange={(e) => agentStore.setAutoApprove(e.currentTarget.checked)}
                        class="checkbox checkbox-xs"
                    />
                    自动审批
                </label>
                <button
                    class="btn btn-ghost btn-sm text-error"
                    onClick={() => { const uri = taskStore.selectedUri; if (uri) agentStore.closeSession(uri); }}
                    disabled={!taskStore.selectedUri}
                >
                    关闭会话
                </button>
                <span class="ml-auto text-xs opacity-60">
                    {agentStore.sending ? "思考中…" : `${agentStore.messages.length} 条消息`}
                </span>
            </div>

            {/* 消息列表 - DaisyUI chat */}
            <div class="flex-1 overflow-auto p-4">
                <Show when={agentStore.messages.length === 0}>
                    <div class="flex items-center justify-center h-full opacity-60 text-sm">
                        在下方输入消息开始与 Agent 对话
                    </div>
                </Show>

                <div class="chat-container space-y-3">
                    <For each={agentStore.messages}>
                        {(msg) => (
                            <div class={`chat ${msg.role === "user" ? "chat-end" : "chat-start"}`}>
                                <div
                                    class={`chat-bubble ${
                                        msg.role === "user"
                                            ? "chat-bubble-primary"
                                            : "chat-bubble-secondary"
                                    }`}
                                >
                                    {msg.content}
                                </div>
                            </div>
                        )}
                    </For>
                </div>

                <Show when={!!agentStore.error}>
                    <div class="text-error text-xs mt-2">{agentStore.error}</div>
                </Show>
                <div ref={bottomRef} />
            </div>

            {/* 输入区 */}
            <div class="flex gap-2 border-t p-2 shrink-0">
                <textarea
                    ref={inputRef}
                    placeholder={agentStore.sending ? "等待回复…" : "输入消息…"}
                    disabled={agentStore.sending}
                    rows={2}
                    class="textarea textarea-bordered flex-1 text-xs"
                    onKeyDown={(e) => {
                        if (e.key === "Enter" && !e.shiftKey) {
                            e.preventDefault();
                            handleSend();
                        }
                    }}
                />
                <button
                    class="btn btn-primary btn-sm self-end"
                    onClick={handleSend}
                    disabled={agentStore.sending}
                >
                    发送
                </button>
            </div>
        </div>
    );
}

// pkgs.ts/diy-app/src/renderer/components-diy/AgentChatPanel.tsx
// src/renderer/components-diy/AgentChatPanel.tsx
import { useEffect, useRef } from "react";
import { useAgentStore } from "./store/agentStore";
import { useTaskStore } from "./store/taskStore";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export function AgentChatPanel() {
  const {
    models,
    activeModel,
    messages,
    sending,
    error,
    autoApprove,
    loadModels,
    syncStatus,
    setModel,
    sendMessage,
    clearChat,
    loadAutoApprove,
    setAutoApprove,
    closeSession,
    switchModel,
  } = useAgentStore();
  const selectedUri = useTaskStore((s) => s.selectedUri);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    loadModels();
    loadAutoApprove();
  }, [loadModels, loadAutoApprove]);
  // 切换任务时以主进程的真实会话状态为准刷新模型，避免界面显示伪造默认值
  useEffect(() => {
    if (selectedUri) void syncStatus(selectedUri);
    else useAgentStore.setState({ activeModel: null });
  }, [selectedUri, syncStatus]);
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const handleSend = () => {
    const el = inputRef.current;
    if (!el || sending) return;
    const text = el.value.trim();
    if (!text) return;
    el.value = "";
    if (!selectedUri) return; // 未选中任务时不发送（task 级对话）
    sendMessage(selectedUri, text);
  };

  return (
    <div className="flex flex-col h-full">
      {/* 顶部：模型选择 + 操作 */}
      <div className="flex items-center gap-2 px-3 py-2 border-b shrink-0">
        <select
          value={activeModel ?? ""}
          onChange={(e) => {
            const id = e.target.value;
            setModel(id);
            // 空值 = 不指定，交给 agent 自己的默认模型；此时不发 set_model
            if (id && selectedUri) switchModel(selectedUri, id);
          }}
          className="h-8 rounded-md border bg-background px-2 text-xs"
        >
          {/* 占位项：没有真实会话时不能预选任何模型，否则视觉上就是「伪造当前值」 */}
          <option value="">（未指定 · 用 agent 默认模型）</option>
          {models.map((m) => (
            <option key={m.id} value={m.id}>
              {m.name}
            </option>
          ))}
        </select>
        <Button variant="ghost" size="sm" className="text-xs" onClick={clearChat}>
          清空
        </Button>
        <label className="flex items-center gap-1 text-xs text-muted-foreground cursor-pointer select-none">
          <input
            type="checkbox"
            checked={autoApprove}
            onChange={(e) => setAutoApprove(e.target.checked)}
            className="h-3 w-3"
          />
          自动审批
        </label>
        <Button
          variant="ghost"
          size="sm"
          className="text-xs text-destructive"
          onClick={() => selectedUri && closeSession(selectedUri)}
          disabled={!selectedUri}
        >
          关闭会话
        </Button>
        <span className="ml-auto text-xs text-muted-foreground">
          {sending ? "思考中…" : `${messages.length} 条消息`}
        </span>
      </div>

      {/* 聊天区 */}
      <ScrollArea className="flex-1 px-3 py-2">
        {messages.length === 0 && (
          <div className="flex items-center justify-center h-full text-muted-foreground text-sm">
            在下方输入消息开始与 Agent 对话
          </div>
        )}
        {messages.map((msg, i) => (
          <div
            key={i}
            className={cn(
              "mb-3 max-w-[80%] rounded-lg px-3 py-2 text-sm leading-relaxed",
              msg.role === "user"
                ? "ml-auto bg-primary text-primary-foreground"
                : "mr-auto bg-muted",
            )}
          >
            {msg.content}
          </div>
        ))}
        {error && <div className="mb-3 text-destructive text-xs">{error}</div>}
        <div ref={bottomRef} />
      </ScrollArea>

      {/* 输入区 */}
      <div className="flex gap-2 border-t p-2 shrink-0">
        <textarea
          ref={inputRef}
          placeholder={sending ? "等待回复…" : "输入消息…"}
          disabled={sending}
          rows={2}
          className="flex-1 resize-none rounded-md border bg-background px-3 py-2 text-xs"
          onKeyDown={(e) => {
            if (e.key === "Enter" && !e.shiftKey) {
              e.preventDefault();
              handleSend();
            }
          }}
        />
        <Button size="sm" onClick={handleSend} disabled={sending}>
          发送
        </Button>
      </div>
    </div>
  );
}
