// pkgs.ts/diy-app/src/renderer/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { bindRendererApi } from "./components-diy/lib/renderer-api-impl";

import "./index.css";
import App from "./App";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";

// Renderer 侧 RPC 服务端 — 处理来自 Main 进程或 CLI 的 RPC 调用
// window.transport 由 preload/index.ts 暴露
if (window.transport) {
  const rendererBinding = bindRendererApi(window.transport);
  // 页面卸载时清理
  window.addEventListener("beforeunload", () => rendererBinding.destroy());
  console.log("[renderer] RPC binding started");
} else {
  console.warn("[renderer] window.transport not available — RPC disabled");
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <TooltipProvider>
      <ThemeProvider>
        <App />
      </ThemeProvider>
    </TooltipProvider>
  </StrictMode>,
);

// pkgs.ts/diy-app/src/renderer_solid/main.tsx
// @ts-nocheck
import { render } from "solid-js/web";
import { bindRendererApi } from "./lib/renderer-api-impl";
import App from "./App";
import "./index.css";

// Renderer 侧 RPC 服务端 — 处理来自 Main 进程或 CLI 的 RPC 调用（diy.ui.*）
// window.transport 由 preload/index.ts 暴露
if ((window as any).transport) {
  const rendererBinding = bindRendererApi((window as any).transport);
  // 页面卸载时清理
  window.addEventListener("beforeunload", () => rendererBinding.destroy());
  console.log("[renderer] RPC binding started");
} else {
  console.warn("[renderer] window.transport not available — RPC disabled");
}

render(() => <App />, document.getElementById("root")!);
