// pkgs.ts/diy-app/src/renderer/components-diy/AppInfo.tsx
// src/renderer/components-diy/AppInfo.tsx
import { useEffect, useState } from "react";

export interface AppInfoData {
  port: number;
  diyHome: string;
  cache: string;
  userData: string;
  electron: string;
  node: string;
  chrome: string;
  platform: string;
  pid: number;
  memory: string;
}

export function AppInfo() {
  const [info, setInfo] = useState<AppInfoData | null>(null);

  useEffect(() => {
    const diy = (window as unknown as Record<string, unknown>).diy as
      | { getAppInfo: () => Promise<AppInfoData> }
      | undefined;
    diy?.getAppInfo().then(setInfo);
  }, []);

  if (!info) {
    return <div className="p-4 text-sm text-muted-foreground">加载中…</div>;
  }

  return (
    <div className="p-4 max-w-xl space-y-2 text-xs font-mono">
      <Section label="运行">
        <Row k="端口" v={String(info.port)} />
        <Row k="PID" v={String(info.pid)} />
      </Section>
      <Section label="目录">
        <Row k="diyHome" v={info.diyHome} />
        <Row k="cache" v={info.cache} />
        <Row k="userData" v={info.userData} />
      </Section>
      <Section label="版本">
        <Row k="Electron" v={info.electron} />
        <Row k="Chrome" v={info.chrome} />
        <Row k="Node.js" v={info.node} />
      </Section>
      <Section label="系统">
        <Row k="平台" v={info.platform} />
        <Row k="内存" v={info.memory} />
      </Section>
    </div>
  );
}

function Section({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="rounded border p-3">
      <div className="text-xs font-bold text-foreground mb-1.5">{label}</div>
      {children}
    </div>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex gap-2">
      <span className="text-muted-foreground w-20 shrink-0">{k}:</span>
      <span className="text-foreground break-all">{v}</span>
    </div>
  );
}

// pkgs.ts/diy-app/src/renderer_solid/components/AppInfo.tsx
import { createSignal, onMount, Show } from "solid-js";

export interface AppInfoData {
  port: number;
  pid: number;
  diyHome: string;
  cache: string;
  userData: string;
  electron: string;
  chrome: string;
  node: string;
  platform: string;
  memory: string;
}

declare global {
  interface Window {
    diy?: {
      getAppInfo?: () => Promise<AppInfoData>;
    };
  }
}

export function AppInfo() {
    const [info, setInfo] = createSignal<AppInfoData | null>(null);
    onMount(() => {
        window.diy?.getAppInfo?.().then(setInfo);
    });
    return (
        <div class="p-4 max-w-xl space-y-2 text-xs font-mono">
            <Show when={info()} fallback={<div class="opacity-60">加载中…</div>}>
                {(i) => (
                    <>
                        <div class="card bg-base-100 border p-3">
                            <div class="font-bold mb-1">运行</div>
                            <Row k="端口" v={String(i().port)} />
                            <Row k="PID" v={String(i().pid)} />
                        </div>
                        <div class="card bg-base-100 border p-3">
                            <div class="font-bold mb-1">目录</div>
                            <Row k="diyHome" v={i().diyHome} />
                            <Row k="cache" v={i().cache} />
                            <Row k="userData" v={i().userData} />
                        </div>
                        <div class="card bg-base-100 border p-3">
                            <div class="font-bold mb-1">版本</div>
                            <Row k="Electron" v={i().electron} />
                            <Row k="Chrome" v={i().chrome} />
                            <Row k="Node.js" v={i().node} />
                        </div>
                        <div class="card bg-base-100 border p-3">
                            <div class="font-bold mb-1">系统</div>
                            <Row k="平台" v={i().platform} />
                            <Row k="内存" v={i().memory} />
                        </div>
                    </>
                )}
            </Show>
        </div>
    );
}
function Row(props: { k: string; v: string }) {
    return (
        <div class="flex gap-2">
            <span class="opacity-60 w-20 shrink-0">{props.k}:</span>
            <span class="break-all">{props.v}</span>
        </div>
    );
}
